packages:
  - 'app'
  - 'worker'
  - 'workflow'
  - 'TrendRadar'
  - 'bridge'

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - rclone.js
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
